Changes required for Qt 5.15
Solves:

../git/src/core/ApplicationDescription.cpp:211:103: error: 'QStringList QString::split(const QString&, QString::SplitBehavior, Qt::CaseSensitivity) const' is deprecated: Use Qt::SplitBehavior variant instead [-Werror=deprecated-declarations]

And

../git/src/platform/webengine/BlinkWebProcessManager.cpp:52:53: error:
'QMap<K, V>::iterator QMap<K, V>::insertMulti(const Key&, const T&)
[with Key = unsigned int; T = QString]' is deprecated: Use QMultiMap for
maps storing multiple values with the same key.
[-Werror=deprecated-declarations]

and

../git/src/platform/webengine/BlinkWebProcessManager.cpp:64:62: error:
'QList<T> QMap<K, V>::values(const Key&) const [with Key = unsigned int;
T = QString]' is deprecated: Use QMultiMap for maps storing multiple
values with the same key. [-Werror=deprecated-declarations]

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>