Fix build with gcc-11
:Release Notes:

:Detailed Notes:
Fixes:
FAILED: src/platform/CMakeFiles/WebAppMgr.dir/webengine/web_page_blink.cc.o
/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/wam/1.0.2-53-r40/recipe-sysroot-native/usr/bin/i686-webos-linux/i686-webos-linux-g++ -DBOOST_ALL_NO_LIB -DBOOST_ATOMIC_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DWebAppMgr_EXPORTS -I/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/wam/1.0.2-53-r40/recipe-sysroot/usr/include/webruntime -I/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/wam/1.0.2-53-r40/git/src/platform -I/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/wam/1.0.2-53-r40/git/src/platform/webengine -I/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/wam/1.0.2-53-r40/recipe-sysroot/usr/include/json-c -I/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/wam/1.0.2-53-r40/git/src/core -I/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/wam/1.0.2-53-r40/git/src/util -I/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/wam/1.0.2-53-r40/git/src/webos -I/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/wam/1.0.2-53-r40/recipe-sysroot/usr/include/glib-2.0 -I/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/wam/1.0.2-53-r40/recipe-sysroot/usr/lib/glib-2.0/include -I/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/wam/1.0.2-53-r40/git/src -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/wam/1.0.2-53-r40/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/wam/1.0.2-53-r40=/usr/src/debug/wam/1.0.2-53-r40                      -fdebug-prefix-map=/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/wam/1.0.2-53-r40=/usr/src/debug/wam/1.0.2-53-r40                      -fdebug-prefix-map=/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/wam/1.0.2-53-r40/recipe-sysroot=                      -fdebug-prefix-map=/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/wam/1.0.2-53-r40/recipe-sysroot-native=  -fvisibility-inlines-hidden   -m32 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/wam/1.0.2-53-r40/recipe-sysroot -fno-rtti -fno-exceptions -Wall -fpermissive -funwind-tables -std=c++14 -Wno-psabi -Werror -DNDEBUG -fPIC -std=gnu++14 -MD -MT src/platform/CMakeFiles/WebAppMgr.dir/webengine/web_page_blink.cc.o -MF src/platform/CMakeFiles/WebAppMgr.dir/webengine/web_page_blink.cc.o.d -o src/platform/CMakeFiles/WebAppMgr.dir/webengine/web_page_blink.cc.o -c /jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/wam/1.0.2-53-r40/git/src/platform/webengine/web_page_blink.cc
/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/wam/1.0.2-53-r40/git/src/platform/webengine/web_page_blink.cc: In member function 'virtual void WebPageBlink::LoadProgressChanged(double)':
/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/wam/1.0.2-53-r40/git/src/platform/webengine/web_page_blink.cc:691:40: error: 'numeric_limits' is not a member of 'std'
  691 |       std::abs(progress - 0.1f) < std::numeric_limits<float>::epsilon();
      |                                        ^~~~~~~~~~~~~~
/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/wam/1.0.2-53-r40/git/src/platform/webengine/web_page_blink.cc:691:55: error: expected primary-expression before 'float'
  691 |       std::abs(progress - 0.1f) < std::numeric_limits<float>::epsilon();
      |                                                       ^~~~~
/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/wam/1.0.2-53-r40/git/src/platform/webengine/web_page_blink.cc: In member function 'double WebPageBlink::DevicePixelRatio()':
/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/wam/1.0.2-53-r40/git/src/platform/webengine/web_page_blink.cc:1076:42: error: 'numeric_limits' is not a member of 'std'
 1076 |       std::abs(ratio_x - ratio_y) < std::numeric_limits<float>::epsilon();
      |                                          ^~~~~~~~~~~~~~
/jenkins/mjansa/build/webos/honister/BUILD/work/qemux86-webos-linux/wam/1.0.2-53-r40/git/src/platform/webengine/web_page_blink.cc:1076:57: error: expected primary-expression before 'float'
 1076 |       std::abs(ratio_x - ratio_y) < std::numeric_limits<float>::epsilon();
      |                                                         ^~~~~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[PLAT-141293] Create GPVB with Yocto 3.4 Honister